version: "2"

services:
  nodeosd:
    build:
      context: .
    image: eosio/eos-dev
    command: /opt/eosio/bin/nodeosd.sh --access-control-allow-origin=* --http-validate-host=false --http-alias=nodeosd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888 --http-alias=0.0.0.0:8888 --delete-all-blocks --contracts-console --data-dir /opt/eosio/bin/data-dir -e
    hostname: nodeosd
    restart: always
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir
      - ./:/eosdev
      
  keosd:
    image: eosio/eos-dev:v1.0.4
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=0.0.0.0:8900
    hostname: keosd
    restart: always
    links:
      - nodeosd
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir

volumes:
  nodeos-data-volume:
    external: true
  keosd-data-volume:
    external: true
